# Generated by Django 4.1.4 on 2022-12-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_picture', models.TextField(max_length=255)),
                ('gift_name', models.CharField(max_length=50)),
                ('gift_price', models.IntegerField()),
                ('on_sale', models.BooleanField(default=False)),
                ('link', models.TextField(max_length=1000)),
                ('tags', models.CharField(max_length=50)),
                ('been_purchased', models.BooleanField(default=False)),
            ],
        ),
    ]
