# Generated by Django 4.1.4 on 2023-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='posted_by',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
