# Generated by Django 4.1.4 on 2023-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_api', '0002_wishlist_posted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='gift_price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
