# Generated by Django 4.1.4 on 2023-01-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to='auth_api.useraccount'),
        ),
    ]
